# Generated by Django 5.0 on 2024-01-07 11:27

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=50, verbose_name='Место')),
                ('time', models.TimeField(default=datetime.time(11, 27, 47, 283395), verbose_name='Время')),
                ('action', models.TextField(verbose_name='Действие')),
                ('sign_of_a_pleasant_habit', models.BooleanField(default=False, verbose_name='Признак приятной привычки')),
                ('periodicity', models.CharField(choices=[('daily', 'ежедневно'), ('every_two_days', 'каждые два дня'), ('every_three_days', 'каждые три дня'), ('very_four_days', 'каждые четыре дня'), ('every_five_days', 'каждые пять дней'), ('every_six_days', 'каждые шесть дней'), ('once_a_week', 'раз в неделю')], max_length=20, verbose_name='Периодичность')),
                ('award', models.TextField(blank=True, null=True, verbose_name='Вознаграждение')),
                ('time_to_complete', models.PositiveIntegerField(verbose_name='Время на выполнение')),
                ('sign_of_publicity', models.BooleanField(default=False, verbose_name='Признак публичности')),
                ('related_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='habits.habit', verbose_name='связанная привычка')),
            ],
            options={
                'verbose_name': 'привычка',
                'verbose_name_plural': 'привычки',
            },
        ),
    ]
