# Generated by Django 5.0 on 2024-01-07 13:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_alter_habit_time_alter_habit_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='time',
            field=models.TimeField(default=datetime.time(13, 8, 30, 237269), verbose_name='Время'),
        ),
    ]
