# Generated by Django 5.0 on 2024-01-07 14:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_alter_habit_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='time',
            field=models.TimeField(default=datetime.time(14, 33, 29, 381629), verbose_name='Время'),
        ),
    ]
