# Generated by Django 5.0 on 2024-01-08 13:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0006_alter_habit_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='time',
            field=models.TimeField(default=datetime.time(13, 14, 56, 932544), verbose_name='Время'),
        ),
    ]
