# Generated by Django 5.0 on 2024-01-08 14:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0008_alter_habit_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='time',
            field=models.TimeField(default=datetime.time(14, 5, 34, 392489), verbose_name='Время'),
        ),
    ]
